default_permissions = "rulesync"

[mcp_servers.openaiDeveloperDocs]
url = "https://developers.openai.com/mcp"

[mcp_servers.context7]
url = "https://mcp.context7.com/mcp"

[mcp_servers.chrome-devtools]
command = "npx"
args = [ "chrome-devtools-mcp@latest" ]

[mcp_servers.deepwiki]
url = "https://mcp.deepwiki.com/mcp"

[features]
hooks = true

[permissions.rulesync.filesystem]
":minimal" = "read"

[permissions.rulesync.network]
enabled = true

[permissions.rulesync.network.domains]
"domain:github.com" = "allow"
"domain:zenn.dev" = "allow"
"domain:raw.githubusercontent.com" = "allow"
